language: python

cache:
    directories:
        - $HOME/.cache/pip

os: linux

jobs:
    include:
        # Ubuntu Xenial (16.04) / Python 3.5
        - dist: xenial
          python: 3.5
          env: TOXENV=py35
        
        # Ubuntu Bionic (18.04) / Python 3.6-3.7
        - dist: bionic
          python: 3.6
          env: TOXENV=py36
        - dist: bionic
          python: 3.7
          env: TOXENV=py37
        
        # Ubuntu Focal (20.04) / Python 3.8+ w/Flake for 3.8
        - dist: focal
          python: 3.8
          env: TOXENV=py38
        - dist: focal
          python: 3.9
          env: TOXENV=py39
        - dist: focal
          python: 3.8
          env: TOXENV=flake8

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#borgbackup"
        use_notice: true
        skip_join: true
