sudo: required

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: xenial
          env: TOXENV=py36
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=py37
        - python: 3.8
          os: linux
          dist: xenial
          env: TOXENV=py38
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=flake8

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#borgbackup"
        use_notice: true
        skip_join: true
